import { Geist, Geist_Mono, Lato } from "next/font/google";
import Header from "../components/common/Header";
import Footer from "../components/common/Footer";
import HtmlSanitizer from "../components/common/HtmlSanitizer"; // we'll create this
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display:'swap',
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display:'swap',
});

const lato = Lato({
  subsets:["latin"],
  weight:["400", "700"],
  variable:"--font-lato",
  display:'swap',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} ${lato.variable} antialiased`}
      >
        <HtmlSanitizer />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
