import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import HtmlSanitizer from "@/src/components/website/common/HtmlSanitizer";
import Header from "@/src/components/website/common/Header";
import Footer from "@/src/components/website/common/Footer";
// import Header from "../components/website/common/Header";
// import Footer from "../components/website/common/Footer";
// import HtmlSanitizer from "../components/website/common/HtmlSanitizer"; // we'll create this

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        suppressHydrationWarning
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <HtmlSanitizer />
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
